### ISSUE TITLE
Last instruction never shown by mapbox

### ISSUE THREAD

**Issue by stoefln** [graphhopper/graphhopper-navigation#23] opened 2019-02-26 10:32 UTC
When I try to navigate a route, the last legStep (arrive) is never executed, therefore I never get a navigation-finished event.

This is the DirectionsRoute I am generating via Graphhopper and Converter:
https://gist.github.com/stoefln/785975e9f917f3ef66b47298e6acceb0

And this is the last step I am getting from the graphhopper navigation onProgressChange callback when I reach the destination (should be the last step, but in fact is the previous to the last one):
```
{
   "distance":11.4,
   "duration":2.3,
   "geometry":"gtj~mAc}ubC??",
   "name":"Carrer del Torrent de les Flors",
   "mode":"driving",
   "maneuver":{
      "location":[
         2.15805,
         41.40834
      ],
      "bearing_before":0.0,
      "bearing_after":0.0,
      "instruction":"Rechts abbiegen auf Carrer del Torrent de les Flors",
      "type":"turn",
      "modifier":"right"
   },
   "voiceInstructions":[
      {
         "distanceAlongGeometry":11.4,
         "announcement":"Ziel erreicht",
         "ssmlAnnouncement":"\u003cspeak\u003e\u003camazon:effect name\u003d\"drc\"\u003e\u003cprosody rate\u003d\"1.08\"\u003eZiel erreicht\u003c/prosody\u003e\u003c/amazon:effect\u003e\u003c/speak\u003e"
      }
   ],
   "bannerInstructions":[
      {
         "distanceAlongGeometry":11.4,
         "primary":{
            "text":"Ziel erreicht",
            "components":[
               {
                  "text":"Ziel erreicht",
                  "type":"text"
               }
            ],
            "type":"arrive"
         }
      }
   ],
   "driving_side":"right",
   "weight":11.4,
   "intersections":[
      {
         "location":[
            2.15805,
            41.40834
         ],
         "bearings":[

         ],
         "entry":[

         ]
      }
   ]
}
```

Any ideas?

**Comment by boldtrn** [comment] 2019-02-26 10:48
Does the same route work via the GraphHopper Directions API? Do you use the simulator or are you actually navigating or mocking the GPS signal?

If the same issue occurs via the Directions API, could you post an example so I can have a look and see if I can reproduce the issue. In my tests the "Ziel erreicht"/"Destination reached" instruction is shown.

**Comment by stoefln** [comment] 2019-02-26 11:55
> Does the same route work via the GraphHopper Directions API? 

I didn't try. we use a local graphhopper instance on the android device. For converting to mapbox format I use the navigation converter locally.

> Do you use the simulator or are you actually navigating or mocking the GPS signal?

I am using a real device with some location mock app

What exactly do you mean by "Directions API"? AFAIS the directions API only returns a GH reponse (I guess that's not the problem here).
I'd rather say it's a conversion problem. Is there some documentation on how to use https://graphhopper.com/api/1/navigate/
?

I could compare the response of the GH navigate endpoint with my own conversion response.

**Comment by boldtrn** [comment] 2019-02-26 13:10
> we use a local graphhopper instance on the android device

IIRC you also had some changes in the response format and an older GH version, so it's hard to know where the issue is created. We need a way to reproduce it :).

> Is there some documentation on how to use https://graphhopper.com/api/1/navigate/

The easiest way is to use the [navigation-example](https://github.com/graphhopper/graphhopper-navigation-example).

An example request would look like this:
`https://graphhopper.com/api/1/navigate/directions/v5/gh/driving/lon,lat;lon,lat?access_token=pk.[GH-KEY]&alternatives=true&geometries=polyline6&overview=full&steps=true&continue_straight=true&annotations=congestion%2Cdistance&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=metric`.

> I could compare the response of the GH navigate endpoint with my own conversion response.

Yes, or maybe use a static json file with the contents of the directions API response to feed to the client.

**Comment by stoefln** [comment] 2019-02-27 09:44
@boldtrn yes, thats right, we use GH v0.82. The response format is basically the same as the one of GH v0.11, there are some minor things missing (U_TURN, KEEP_LEFT, KEEP_RIGHT), but that's certainly not the issue here.  
Thanks for the endpoint param spec. I tried to compare my response against the response of https://graphhopper.com/api/1/navigate/ but unfortunately it seems to route differently, so it's hard to figure out if there is something wrong with my implementation.

A mate of mine implemented the converter himself (without using your code) on iOS and it works perfectly fine for him. I checked his converted format and found a couple of differences. Two questions popped up:

1. he is generating the bearings, and said that his mock drive was also getting stuck before implementing them. Are you sure it's fine to not have them?
2. he seems generate the polylines differently. His polylines can be easily shown with [this tool](https://developers.google.com/maps/documentation/utilities/polylineutility), compared to polylines generated by your converter (or the GH navigation API), which don't seem to be decodable with this tool. Any idea?

**Comment by boldtrn** [comment] 2019-02-27 18:07
> he is generating the bearings, and said that his mock drive was also getting stuck before implementing them. Are you sure it's fine to not have them?

I am not sure :). We tested with [this client](https://github.com/graphhopper/graphhopper-navigation-example) and I have seen the last instruction and also heard the arrive instruction.

> he seems generate the polylines differently. His polylines can be easily shown with [this tool](https://developers.google.com/maps/documentation/utilities/polylineutility), compared to polylines generated by your converter (or the GH navigation API). When trying to decode, the resulting values are 10x of what they should be. So instead of a longitude of 2.x, we end up with a longitude of 20.x. Any idea?

That's related to the the polyline precision. The converter currently only supports polyline6. It uses 6 decimal places instead of the regular 5 decimal places. Currently the client we use only supports polyline6. This should be easy to change though, [here](https://github.com/graphhopper/graphhopper-navigation/blob/master/src/main/java/com/graphhopper/navigation/NavigateResponseConverter.java#L152) and [here](https://github.com/graphhopper/graphhopper-navigation/blob/master/src/main/java/com/graphhopper/navigation/NavigateResponseConverter.java#L76). A PR adding this as a [request parameter](https://docs.mapbox.com/api/navigation/#directions) via `geometries=geojson|polyline|polyline6` would be welcome and should be pretty straight forward :).

**Comment by karussell** [comment] 2019-02-27 18:50
I suggest closing here as we can only support 0.11 onwards.

**Comment by stoefln** [comment] 2019-02-28 11:41
thanks @boldtrn didn't figure out whats wrong but feel free to close it, yes

**Comment by boldtrn** [comment] 2019-03-01 08:06
Ok, will close this issue.

**Closed by boldtrn** 2019-03-01 08:06 UTC
